from building import * 
import rtconfig

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = Glob('*.c')
inc = [cwd]

LOCAL_CCFLAGS = ''

group = DefineGroup('Utils', src, depend = [''], CPPPATH = inc, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')